site_name: LinkUp Blog
site_url: https://blog.link-up.co.il/
theme:
  name: material
  custom_dir: overrides
  language: he
  logo: assets/logo.png
  favicon: images/favicon.png
  font:
    text: Noto Sans Hebrew
    code: Roboto Mono
  features:
    - navigation.footer

markdown_extensions:
  - tables

